print("meu nome é john ")
print("minha idade é 11 anos")
print("eu moro em dermerval lobão")
numero1 = input("qual seu nome")
numero2 = input("qual sua idade")
funciona = numero1 + numero2
print("seu nome é", numero1, "e sua idade é", numero2)
print("agora vamos fazer uma soma")
numero3= input("qual o primeiro número")
numero4 = input("qual o segundo número")
soma = int(numero3) + int(numero4)
print("a soma dos números é", soma)
